
title: Alsox Sistema-5
email: alccpe@yahoo.com.br
description: "Meu site pessoal em fase de desenvolvimento"
baseurl: "" # Esse vai ser meu alsoxsistemas5.com.br
url: "" 
twitter_username: alsoxSoftware
github_username:  alsoxSoftware

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
theme: minima
plugins:
  - jekyll-feed
