
title: Alsox Blog
email: alccpe@yahoo.com.br
description: "Meu site pessoal em fase de desenvolvimento"
baseurl: "" # Esse vai ser meu www.alsox5.com.br
url: "www.alsox5.com.br" 
twitter_username: 
github_username:  alsox5

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
theme: minima
plugins:
  - jekyll-feed
